- pipeline.id: es01
  path.config: "/usr/share/logstash/pipeline/logstash01.conf"
  pipeline.workers: 1
- pipeline.id: es02
  path.config: "/usr/share/logstash/pipeline/logstash02.conf"
  pipeline.workers: 1