---
actions:
  1:
    action: allocation
    description: >-
      Apply shard allocation filtering rules to logstash-* prefixed indices that are
      older than 1 day. These indices will move their shards from hot to warm nodes.
    options:
      key: data
      value: warm
      allocation_type: require
      wait_for_completion: true
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
  2:
    action: forcemerge
    description: >-
      Performs a force merge operation on logstash-* prefixed indices that are older than 2 days. At this point these should be read only, it's best to avoid writing to these indices once optimized.
    options:
      max_num_segments: 1
      delay:
      ignore_empty_list: True
      timeout_override: 21600
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
