---
actions:
  1:
    action: snapshot
    description: >-
      Snap shots all prefix based 'logstash-*' indices.
    options:
      repository: logstash_backup_repository
      name: logstash-snapshots
      wait_for_completion: True
      max_wait: 3600
      wait_interval: 10
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
